name: flutter_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

flutter_native_splash:
  image: assets/common/launch.png
  color: "#000000"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons:

  fluro: ^2.0.5

  # 打印
  stack_trace:

  # 打开外部应用
  url_launcher:

  #提示
  fluttertoast:

  #播放视频
  video_player:

  #加载本地文件
  path_provider:

  #上拉下拉
  flutter_easyrefresh:

  # loading
  flutter_easyloading:

  # 蓝牙
  # flutter_blue:
  flutter_blue_plus: 1.4.0

  #瀑布流
  flutter_staggered_grid_view:

  #本地存储
  shared_preferences:

  #版本号
  package_info:



dev_dependencies:
  #闪屏
  flutter_native_splash:

  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/home/
    - assets/common/
    - assets/set/
    - assets/faba/
    - assets/radio/
    - assets/speaker/
    - assets/play/
    - assets/rgb/

  fonts:
      - family: Mont
        fonts:
          - asset: assets/fonts/Mont-Regular.otf
            weight: 400
          - asset: assets/fonts/Mont-Bold.otf
            weight: 700
          - asset: assets/fonts/Mont-RegularItalic.otf
            style: italic
flutter_intl:
  enabled: true
